# AWS SAM template to provision AWS resources
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures: # pick the correct arch for your laptop :)
      - arm64
      # - x86_64
    MemorySize: 512
    Timeout: 60
    Environment:
      Variables:
        AWS_DEFAULT_REGION: ap-southeast-1
        NODE_ENV: dev
        JWT_SECRET: jwt-secret
        DYNAMO_DB_ENDPOINT: http://host.docker.internal
        DYNAMO_DB_PORT: 8000
        JWT_SECRET_KEY: verySecretOne
        SHA256_SECRET_KEY: verySecretOne

Resources:
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/functions/products.handler
      Events:
        DirectPost:
          Type: Api
          Properties:
            Path: /products
            Method: POST
        DirectPut:
          Type: Api
          Properties:
            Path: /products
            Method: PUT
        DirectGet:
          Type: Api
          Properties:
            Path: /products
            Method: GET
        DirectDelete:
          Type: Api
          Properties:
            Path: /products
            Method: DELETE
        CatchAllPost:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: POST
        CatchAllPut:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: PUT
        CatchAllGet:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: GET
        CatchAllDelete:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: DELETE
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/functions/auth.handler
      Events:
        DirectPost:
          Type: Api
          Properties:
            Path: /auth
            Method: POST
        CatchAllPost:
          Type: Api
          Properties:
            Path: /auth/{proxy+}
            Method: POST
  PreflightFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/functions/preflight.handler
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
